COUNTRY_GROUPS = {
    "India": 1,
    "Liberia": 2,
    "Ethiopia": 2,
    "Tanzania": 2,
    "Senegal": 2,
    "Kenya": 2,
    "Pakistan": 2,
    "Ivory Coast": 2,
    "Nigeria": 2,
    "Ghana": 2,
    "Morocco": 2,
    "Guatemala": 2,
    "Philippines": 2,
    "Vietnam": 2,
    "El Salvador": 2,
    "Venezuela": 2,
    "Paraguay": 2,
    "Indonesia": 2,
    "Ukraine": 2,
    "Algeria": 2,
    "Armenia": 2,
    "Egypt": 2,
    "South Africa": 2,
    "Peru": 2,
    "Lebanon": 2,
    "Colombia": 2,
    "Georgia": 2,
    "Brazil": 2,
    "Azerbaijan": 2,
    "Serbia": 2,
    "Costa Rica": 2,
    "Mexico": 2,
    "Belarus": 2,
    "Mauritius": 2,
    "Argentina": 2,
    "Bulgaria": 2,
    "Thailand": 3,
    "Chile": 3,
    "Kazakhstan": 3,
    "Malaysia": 3,
    "Panama": 3,
    "Turkey": 3,
    "Trinidad and Tobago": 3,
    "Russia": 3,
    "Croatia": 3,
    "Romania": 3,
    "Oman": 3,
    "Latvia": 3,
    "Greece": 3,
    "Hungary": 3,
    "Slovakia": 3,
    "Portugal": 3,
    "Poland": 3,
    "Lithuania": 3,
    "Estonia": 3,
    "Slovenia": 3,
    "Czech Republic": 3,
    "Seychelles": 3,
    "Bahamas": 3,
    "China": 4,
    "Cyprus": 4,
    "Spain": 4,
    "Italy": 4,
    "Israel": 4,
    "Malta": 4,
    "New Zealand": 4,
    "France": 4,
    "Canada": 4,
    "Taiwan": 4,
    "Australia": 4,
    "United States": 4,
    "Belgium": 4,
    "Finland": 4,
    "Austria": 4,
    "Bahrain": 4,
    "Netherlands": 4,
    "Norway": 4,
    "Ireland": 4,
    "Holy See": 4,
    "South Korea": 5,
    "Japan": 5,
    "Saudi Arabia": 5,
    "United Kingdom": 5,
    "United Arab Emirates": 5,
    "Sweden": 5,
    "Germany": 5,
    "Qatar": 5,
    "Denmark": 5,
    "Hong Kong": 5,
    "Luxembourg": 5,
    "Switzerland": 5,
    "Singapore": 5,
    "Macau": 5,
    "Monaco": 5,
    "Liechtenstein": 5,
    "Iceland": 5,
    "Andorra": 5,
    "Brunei": 5,
    "Puerto Rico": 3,
    "Dominican Republic": 2,
    "Ecuador": 2,
    "Uruguay": 2,
    "Cabo Verde": 2,
    "Congo": 2,
    "Eswatini": 2,
    "Kuwait": 2,
    "Afghanistan": 2,
    "Albania": 2,
    "Angola": 2,
    "Antigua and Barbuda": 2,
    "Bangladesh": 2,
    "Barbados": 2,
    "Belize": 2,
    "Benin": 2,
    "Bhutan": 2,
    "Bolivia": 2,
    "Bosnia and Herzegovina": 2,
    "Botswana": 2,
    "Burkina Faso": 2,
    "Burundi": 2,
    "Cameroon": 2,
    "Central African Republic": 2,
    "Chad": 2,
    "Comoros": 2,
    "Cuba": 2,
    "Democratic Republic of the Congo": 2,
    "Djibouti": 2,
    "Dominica": 2,
    "Equatorial Guinea": 2,
    "Eritrea": 2,
    "Fiji": 2,
    "Gabon": 2,
    "Gambia": 2,
    "Grenada": 2,
    "Guinea": 2,
    "Guinea-Bissau": 2,
    "Guyana": 2,
    "Haiti": 2,
    "Honduras": 2,
    "Iran": 2,
    "Iraq": 2,
    "Jamaica": 2,
    "Kiribati": 2,
    "Kyrgyzstan": 2,
    "Laos": 2,
    "Lesotho": 2,
    "Libya": 2,
    "Madagascar": 2,
    "Malawi": 2,
    "Maldives": 2,
    "Mali": 2,
    "Marshall Islands": 2,
    "Mauritania": 2,
    "Micronesia": 2,
    "Moldova": 2,
    "Mongolia": 2,
    "Montenegro": 2,
    "Mozambique": 2,
    "Myanmar": 2,
    "Namibia": 2,
    "Nauru": 2,
    "Nepal": 2,
    "Niger": 2,
    "North Korea": 2,
    "North Macedonia": 2,
    "Palau": 2,
    "Palestine": 2,
    "Papua New Guinea": 2,
    "Rwanda": 2,
    "Saint Kitts and Nevis": 2,
    "Saint Lucia": 2,
    "Saint Vincent and the Grenadines": 2,
    "Samoa": 2,
    "San Marino": 2,
    "Sao Tome and Principe": 2,
    "Sierra Leone": 2,
    "Solomon Islands": 2,
    "Somalia": 2,
    "South Sudan": 2,
    "Sri Lanka": 2,
    "Sudan": 2,
    "Suriname": 2,
    "Syria": 2,
    "Tajikistan": 2,
    "Timor-Leste": 2,
    "Togo": 2,
    "Tonga": 2,
    "Tunisia": 2,
    "Turkmenistan": 2,
    "Tuvalu": 2,
    "Uganda": 2,
    "Uzbekistan": 2,
    "Vanuatu": 2,
    "Yemen": 2,
    "Zambia": 2,
    "Zimbabwe": 2,
    "Cambodia": 2,
    "Jordan": 2,
    "Nicaragua": 2,
    "USA": 4,
    "US": 4,
    "U.S.": 4,
    "U.S.A.": 4,
    "United States of America": 4,
    "Korea": 5,
    "Republic of Korea": 5,
    "S. Korea": 5,
    "Czechia": 3,
    "Côte d'Ivoire": 2,
    "Republic of Côte d'Ivoire": 2,
    "Cote D'Ivoire": 2,
    "UK": 5,
    "Great Britain": 5,
    "U.K.": 5,
    "England": 5,
}
GROUP_1 = ",\n".join([x for x in COUNTRY_GROUPS if COUNTRY_GROUPS[x] == 1])
GROUP_2 = ",\n".join([x for x in COUNTRY_GROUPS if COUNTRY_GROUPS[x] == 2])
GROUP_3 = ",\n".join([x for x in COUNTRY_GROUPS if COUNTRY_GROUPS[x] == 3])
GROUP_4 = ",\n".join([x for x in COUNTRY_GROUPS if COUNTRY_GROUPS[x] == 4])
GROUP_5 = ",\n".join([x for x in COUNTRY_GROUPS if COUNTRY_GROUPS[x] == 5])
SHEET_KEY = "1zLASxBWTH-FYK_K5SAbNQoVtDg7N4mFMHj_-_9GUASw"
WORKSHEET = "Pricing Output"
INPUT_TO_CELL_NO_HEATMAP = {
    "model_type": "CH26",
    "include_dependents": "CH27",
    "disc.": "CH30",
    "therapy_sessions": "CH31",
    "coaching_sessions": "CH32",
    "deskless_population": "CH33",
    "year": "CH34",
    "phone": "CH37",
    "crisis": "CH38",
    "worklife": "CH39",
    "supervisory": "CH40",
    "mandatory_referral": "CH41",
    "health_plan_integration": "CH42",
    "psychiatry_and_medication_management": "CH43",
    "counseling_sessions_covered_by_eap": "CH44",
    "private_circles": "CH45",
    "group_1": "CH48",
    "group_2": "CH49",
    "group_3": "CH50",
    "group_4": "CH51",
    "group_5": "CH52",
}
INPUT_TO_CELL_HEATMAP = {
    "model_type": "CH26",
    "include_dependents": "CH27",
    "disc.": "CH30",
    "therapy_sessions": "CH31",
    "coaching_sessions": "CH32",
    "deskless_population": "CH33",
    "year": "CH34",
    "phone": "CH37",
    "crisis": "CH38",
    "worklife": "CH39",
    "supervisory": "CH40",
    "mandatory_referral": "CH41",
    "health_plan_integration": "CH42",
    "psychiatry_and_medication_management": "CH43",
    "counseling_sessions_covered_by_eap": "CH44",
    "private_circles": "CH45",
}
